name: CI
on: [push, pull_request]
jobs:
  # test-windows:
  #   environment: Test
  #   name: Run Tests on Windows
  #   runs-on: ${{ matrix.os }}
  #   if: "!contains(github.event.head_commit.message, 'ci skip')"
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [windows-latest]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Test
  #     shell: pwsh
  #     run: ./build.ps1 -Task Test -Bootstrap
  test-mac:
    environment: Test
    name: Run Tests on macOS
    runs-on: [self-hosted, macOS, x64]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v1
    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
  test-linux:
    environment: Test
    name: Run Tests on Linux
    runs-on: [self-hosted, linux, x64]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v1
      name: Test
    - uses: actions/setup-pwsh
      name: Set up pwsh
    - run: ./build.ps1 -Task Test -Bootstrap
      shell: pwsh
      name: Run build.ps1 Test Bootstrap
