name: CI
on: [push, pull_request]
jobs:
  test:
    environment: Test
    name: Run Tests
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Test
      shell: pwsh
      run: $env:PixooIP = ${{secrets.PIXOOIP}};./build.ps1 -Task Test -Bootstrap
